### ISSUE TITLE
Idea: use mkdocs-print-page to print all website

### ISSUE THREAD

**Issue by cspaier** [adrienbrignon/mkdocs-exporter#12] opened 2023-11-26 19:51 UTC
I see in the roadmap: 
> Combine all pages as one PDF

And I know that [mkdocs-print-site](https://github.com/timvink/mkdocs-print-site-plugin) does one thing: automatically create a page served at `/print_page` that combine all  pages of the site.

I thought I just had to combine your plugins and the `print-site` one to have a neat pdf of all my documentation.

This failed with a `playwright._impl._errors.TimeoutError` :( If you ever get curious, you can find the full traceback in [this gist](https://gist.github.com/cspaier/c2b3570e5c068fba5f69e9d81675aa08).

So I was wondering if you were aware of this `print-site-plugin`. Anyway, you may want to handle this feature by yourself to get more control of the process.

**Comment by adrienbrignon** [comment] 2023-11-28 17:53
Hello @cspaier,

Thank you for opening an issue and for all the details you've provided.

The timeout is caused by an issue during the "preview" generated by [Paged.js](https://github.com/pagedjs/pagedjs). Maybe the page contains too much elements and it fails? Disabling the [browser's headless mode](https://github.com/adrienbrignon/mkdocs-exporter/blob/a5c5f502132585097cb2ac616af7352a11e033a8/mkdocs_exporter/plugins/pdf/browser.py#L51) (not available through configuration, though) and heading to the JavaScript console of the page should give you more details.

About [`mkdocs-print-site-plugin`](https://github.com/timvink/mkdocs-print-site-plugin), yes, I have used it in the past and was quite happy with it :)
In the future, this feature will be handled by the plugin itself so compatibility can be ensured at all times.

I am currently rewriting the plugin, the logic will now be mainly written in JavaScript so interactions can now be done directly between the browser and the page to render PDF documents on the fly.

You can find some more details [here](https://github.com/adrienbrignon/mkdocs-exporter/issues/10#issuecomment-1808821574).

**Comment by adrienbrignon** [comment] 2024-06-07 21:35
This feature has been released in the [`v6.0.0`](https://github.com/adrienbrignon/mkdocs-exporter/releases/tag/v6.0.0) version.

Thank you for your patience, I will now close this issue.

**Closed by adrienbrignon** 2024-06-07 21:35 UTC
Labels: enhancement, good first issue

**Comment by cspaier** [comment] 2024-06-07 21:49
Thank you for your work.
